### ISSUE TITLE
Replace md5 by secure hash algorithm like sha256

### ISSUE THREAD

**Issue by thardeck** [cloudfoundry/buildpack-packager#17]
Are there any plans to replace the insecure md5 hash algorithm in the packager by a secure one like sha256?

**Comment by sclevine** [comment]
Hi @thardeck,

Yes, eventually we plan to do this. I'll prioritize this story so you can follow it in our backlog.

**Comment by sclevine** [comment]
@thardeck This is finished. All buildpacks use sha256 checksums on their `develop` branch.
