### ISSUE TITLE
How to create a very simple build pack

### ISSUE THREAD

**Issue by jaisonpjohn** [cloudfoundry/buildpack-packager#22]
All I need to do in the buildpack is,
```echo "$KAFKA_TRUSTSTORE_CERT" | base64 --decode > $BUILD_DIR/BOOT-INF/classes/kafka.truststore.jks```

My application is expecting a file which contains some confidential info. I could pass that as environment variable. This buildpack will read that env variable and write to local file system. I need a simple minimal buildpack for wrapping just this function. how can I do that

**Comment by Zanadar** [comment]
https://docs.cloudfoundry.org/buildpacks/custom.html has docs that could help you

**Comment by jaisonpjohn** [comment]
@Zanadar No, it doesnt, otherwise I wouldnt bother to raise an issue here. I am new to CloudFoundry, I couldnot find a single document mentioning how to create a simple buildpack which invokes a shell script

**Comment by Zanadar** [comment]
@jaisonpjohn Apologies, I didn't intend to be dismissive.  Buildpacks can be confusing at first. Basically . you need a bin/ directory with bin/detect, bin/supply, and bin/finalize. Detect should exit 0, supply should do you thing, and finalize does nothing.

https://docs.cloudfoundry.org/buildpacks/understand-buildpacks.html has better docs. I'll add more information and an example in a bit.

**Comment by jaisonpjohn** [comment]
@Zanadar No worries, I did not feel it as dismissive, its all good. Thanks for the info.

**Comment by dfreilich** [comment]
Hey @jaisonpjohn , I hope that the above helped! I'm going to close the issue, but feel free to reopen, or engage with us on the cloud foundry slack if you need more help writing a buildpack!
