### ISSUE TITLE
README explanation 

### ISSUE THREAD

**Issue by jasonjackson** [cloudfoundry/buildpack-packager#6]
It would be great to get a little more context on how to get started with this, or better understand how to use it and what it's used for.  I cloned the repo and bundle installed, see the buildpack-packager in bin, but can't really infer much beyond that on how to use it.

Is there a gem source i need to be aware of?  Do i copy a manifest.yml into that bin directory?  Do i copy that buildpack-packager bin to the git checkout of where my manifest is?  I tried all of the above, but am only getting errors..

A little context around how you actually use it would be awesome...   Thanks!

**Comment by flavorjones** [comment]
Hi @jasonjackson,

Thanks for asking these questions. Generally speaking, this library is declared as a Gemfile dependency in your (custom?) buildpack. Its purpose is to package up rootfs-specific binaries into the buildpack; generally these binaries are the ones necessary for the buildpack to operate in a disconnected CF environment.

Can ask what you're trying to do? What are the specific errors you're getting?

**Comment by flavorjones** [comment]
Closing, pending response from OP. Plus, I think we've added some meaningful content to the README in the meantime.
